import javax.swing.*;

public class AdminGUI {
    private JPanel panel1;
    private JList list1;
    private JList list2;
    private JComboBox comboBox1;
    private JComboBox comboBox2;
    private JComboBox comboBox3;
    private JComboBox comboBox4;
    private JComboBox comboBox5;
    private JButton createCourseButton;
    private JButton viewCourseDetailsButton;
    private JButton viewRoomDetailsButton;
    private JButton mainMenuButton;
    private JButton preferencesButton;
    private JButton editUsersButton;
    private JButton logOutButton;
    private JButton createNewCourseButton;
    private JButton editCoursesAndRoomsButton;
    private JTabbedPane tabbedPane1;
    private JList list3;
    private JTextField textField1;
    private JButton addButton;
    private JButton deleteSelectedCourseButton;
    private JButton mainMenuButton1;
    private JList list4;
    private JTextField textField2;
    private JButton addButton1;
    private JButton deleteSelectedRoomButton;
    private JButton mainMenuButton2;
    private JButton addRemoveStudentsFromButton;
    private JList list5;
    private JList list6;
    private JButton addStudentToAButton;
    private JButton removeStudentFromSelectedButton;
    private JButton mainMenuButton3;
    private JList list7;
    private JList list8;
    private JList list9;
    private JButton changeRoomButton;
    private JButton mainMenuButton4;
    private JTextField textField3;
}
